#!/usr/bin/env -S deno run -A --ext=ts

import $ from "https://deno.land/x/dax/mod.ts";

if (Deno.args.length == 0) {
  console.log(JSON.stringify({
    title: "Tailcale",
    commands: [
      {
        name: "list-devices",
        title: "Search My Devices",
        mode: "view",
      },
    ],
  }));

  Deno.exit(0);
}

if (Deno.args[0] == "list-devices") {
  const status = await $`tailscale status --json`.json();
  const devices = Object.values(status.Peer) as any[];
  const items = devices.map((device) => ({
    title: device.DNSName.split(".")[0],
    subtitle: device.TailscaleIPs[0],
    accessories: [device.OS, device.Online ? "online" : "offline"],
    actions: [
      {
        title: "Copy SSH Command",
        onAction: {
          type: "copy",
          text: `ssh ${device.TailscaleIPs[0]}`,
          exit: true,
        },
      },
      {
        title: "Copy IP",
        onAction: {
          type: "copy",
          text: device.TailscaleIPs[0],
          exit: true,
        },
      },
    ],
  }));

  console.log(JSON.stringify({ type: "list", items }));
}
